chanmged virtual environment
Installing in another virtual environmnet as r-reticulate leads to an error:
 Error in py_module_import(module, convert = convert) :
   ModuleNotFoundError: No module named 'eikon'

by changing to main environment r-reticulate this does not occur